### ISSUE TITLE
Error in Error template

### ISSUE THREAD

**Issue by tillnelown** [revanced/revanced-integrations#103]
### Type

Other

### Bug description

The "Solution" field in the Error template says it's optional but it isn't.

### Steps to reproduce

Create a bug and try to leave the "Solution" field empty.

### Relevant log output

```shell
None
```

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/47001331/181300266-b7e623b8-ab38-4129-b98b-45795bdcb012.png)

### Solution

abcde

**Comment by Sculas** [comment]
Fixed in #104.
