### ISSUE TITLE
[Suggestion] Rename Releases

### ISSUE THREAD

**Issue by YonLiud** [revanced/revanced-integrations#11]
## First of all congratulations on the Release of version 0.5.0! can't wait for the full version of 1.0.0

Although here's a suggestion:
### Rename [app-release-unsigned.apk](https://github.com/revanced/revanced-integrations/releases/download/v0.5.0/app-release-unsigned.apk) to revanced-integrations-v05.apk or something alike to not cause confusion among files and release versions

<sup><sub>PS plz unban I did nothing wrong in my PR and yet got banned off discord #9  </sub></sup>

**Comment by oSumAtrIX** [comment]
Please contact me at osumatrix@revanced.app

**Comment by Indranil012** [comment]
should be closed now
