### ISSUE TITLE
Integration flag

### ISSUE THREAD

**Issue by cyberboh** [revanced/revanced-integrations#14]
Need a clear instructions about flagas thats supportted till now:
I only know some of them , like `-i amoled, -i shorts-button -i minimized-playback -i old-quality-layout -i disable-create-button -i general-ads -i video-ads -i seekbar-tapping -i upgrade-button-remover -i tasteBuilder-remover -i background-play`

**Comment by oSumAtrIX** [comment]
Use --help to find out about all the commands.

**Comment by cyberboh** [comment]
> Use --help to find out about all the commands.

does not work , sir

`java -jar integrations.apk -help`
`Error: Invalid or corrupt jarfile integrations.apk`

**Comment by cyberboh** [comment]
> 

This 
`E:\ReVanced>java -jar revanced-cli-1.4.2-all.jar --help
Usage: ReVanced-CLI [-chlrV] [--debugging] [--install] -a=<inputFile>
                    [--cn=<cn>] [-d=<deploy>] -o=<outputPath> [-p=<password>]
                    [-t=<cacheDirectory>] [-b=<patchBundles>]...
                    [-i=<includedPatches>]... [-m=<mergeFiles>]...
  -a, --apk=<inputFile>      Input file to be patched
  -b, --bundles=<patchBundles>
                             One or more bundles of patches
  -c, --clean                Clean the temporal resource cache directory. This
                               will be done anyways when running the patcher
      --cn=<cn>              Overwrite the default CN for the signed file
  -d, --deploy-on=<deploy>   If specified, deploy to adb device with given name
      --debugging            Disable patch version compatibility
  -h, --help                 Show this help message and exit.
  -i, --include=<includedPatches>
                             Which patches to include. If none is specified,
                               all compatible default patches will be included
      --install              If specified, instead of mounting, install
  -l, --list                 List patches only
  -m, --merge=<mergeFiles>   One or more dex file containers to merge
  -o, --out=<outputPath>     Output file path
  -p, --password=<password>  Overwrite the default password for the signed file
  -r, --resource-patcher     Disable patching resources
  -t, --temp-dir=<cacheDirectory>
                             Temporal resource cache directory
  -V, --version              Print version information and exit.

E:\ReVanced>`

I can not find the command list of integration flag

**Comment by CnC-Robert** [comment]
Read the docs its explained in there
