### ISSUE TITLE
feat: Wider padding on 1% brightness for Swipe controls

### ISSUE THREAD

**Issue by MormonBoy** [ReVanced/revanced-integrations#156]
### Type

Functionality

### Issue

Currently to set the phone on minimum brightness required an incredibly steady hand to not swing down to automatic or up to 5-6%. 

### Feature

There should be a larger 'notch' at which minimum brightness can be selected or the 'Auto' setting should be at the top. It should be a trivial experience to set your device to minimum brightness. 1% brightness should also be relabeled as 'minimum' or a similar alternative for ease of user experience and understanding. I often find myself trying to adjust the brightness with the built in slider so I can just leave it on minimum brightness, but I am unable to use the android brightness slider while the app is open.

### Motivation

I, like many others, often watch YouTube in bed at night and would like the absolute minimum brightness I can possibly have to not strain my eyes in the dark. Currently it is incredibly tedious to try and adjust the brightness to minimum and it would be a great benefit to me and I'm sure to many others to make this an easier solution. A great quality of life change.

**Comment by oSumAtrIX** [comment]
A duplicate issue exists in the `revanced-patches` repository
