### ISSUE TITLE
[Suggestion] Refactor Integrations

### ISSUE THREAD

**Issue by TheJeterLP** [revanced/revanced-integrations#16]
I would like to contribute to revanced by refactoring the integrations and cleaning up the codebase. Like creating a new package where all the classes from original vanced are being stored and just cleanup everything.
I saw that multiple Patches depend on the same classes in integrations. For a code cleanup this should be changed. I want to do that too.

**Comment by TheJeterLP** [comment]
This will take a long time tho since I have to learn how the whole integration classes work and are combined together

**Comment by Canny1913** [comment]
i dont think 15 hours is long :D
great freaking job btw

**Comment by Canny1913** [comment]
oh damn

**Comment by TheJeterLP** [comment]
Just wanted to create draft PRs so team can see whats happening

**Comment by oSumAtrIX** [comment]
Good job and thanks for this massive contribution
