### ISSUE TITLE
feat: option to wait for Sponsorblock segments before playing a video

### ISSUE THREAD

**Issue by svgPhoenix** [revanced/revanced-integrations#172]
### Type

Functionality

### Issue

Videos with segments at the beginning may start playing before the sponsorblock segments load, missing some or all of a segment that should've been skipped 

### Feature

Create a setting to wait a user-defined amount of time (default 300\500ms?) before playing the video.

### Motivation

It is an annoyance that most users of the app will doubtless experience at some point, especially when connected to cellular data

**Comment by oSumAtrIX** [comment]
Loading videos slow is a bad experience imo. I rather load the video quickly instead of having to wait addition x seconds.

**Comment by svgPhoenix** [comment]
That's why I proposed adding it as a toggle in settings and making the time user-defined. It would probably be best to have it off by default, but I'm pretty sure this feature exists in the SmartTube Android TV client so I don't see why duplicating it here would be an issue

**Comment by oSumAtrIX** [comment]
As i said, any additional delay bigger than 0 is contra-productive, what you want is for SponsorBlock to skip the segment after it loads.

**Comment by svgPhoenix** [comment]
Isn't the whole ethos of this project that the users should decide how they want to watch the videos? I understand completely if you don't want to develop this feature but please stop telling me that I'm wrong for being frustrated when my videos start with a word that gets cut in half when segments load.
