### ISSUE TITLE
bug: The separator not working well on Xiaomi Redmi Note 11

### ISSUE THREAD

**Issue by YT-Advanced** [revanced/revanced-integrations#276]
### Type

Cosmetic

### Bug description

As you can see below, the separator is not work properly

### Steps to reproduce

None

### Relevant log output

```shell
None
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/70064328/211012814-95bce8d1-b46a-4a82-9900-fa7a790b14e7.png)

### Solution

I think the bug cause by the system font (MiSans)

### Additional context

Device: Xiaomi Redmi Note 11
Android: 12 (MIUI 13)
System font: MiSans (it's the default one)

**Comment by LisoUseInAIKyrios** [comment]
Post a picture of non dark mode

**Comment by LisoUseInAIKyrios** [comment]
It's bizarre the MiSans font does not recognize different colors, but glad you got it fixed.
