### ISSUE TITLE
Custom settings needs a context

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-integrations#30]
As the title already suggests: latest version of Vanced use a patch to acquire a necessary context, to make the app working with custom settings page (app will crash otherwise).

Same patch could be found on YouTube Music too.

**Comment by OxrxL** [comment]
https://github.com/revanced/revanced-integrations/pull/29

**Comment by oSumAtrIX** [comment]
Please explain the problem and propose a solution

**Comment by OxrxL** [comment]
> Please explain the problem and propose a solution. I don't know what you mean or what you refer to.

Detailed explanation: to get (or overwrite) the current status of a preference (with the sharedpreference method) you need to specify a context, acquired directly from the application. In the absence of the latter, if you try to use the sharedpreference method, the app crashes.

Solution: it doesn't seem to be required, because it is already present in the integrations and points directly to an existing file in the apk:
<img width="476" alt="Immagine 2022-06-30 113859" src="https://user-images.githubusercontent.com/108184954/176646470-89eacb54-e714-4352-9084-b4de3b6c1100.png">

**Comment by OxrxL** [comment]
> XFileDebug is never used. So you should actually look at the latest version of Integrations. But yes, that already exists

This method is used by some sharedpreference to enable or disable features. XFILEDEBUG is not important.

**Comment by TheJeterLP** [comment]
> > XFileDebug is never used. So you should actually look at the latest version of Integrations. But yes, that already exists
> 
> This method is used by some sharedpreference to enable or disable features. XFILEDEBUG is not important.

Correct. It was. Please use the latest Integrations version for posting code and looking at code.

**Comment by OxrxL** [comment]
> > > XFileDebug is never used. So you should actually look at the latest version of Integrations. But yes, that already exists
> > 
> > 
> > This method is used by some sharedpreference to enable or disable features. XFILEDEBUG is not important.
> 
> Correct. It was. Please use the latest Integrations version for posting code and looking at code.

Right. Screenshots must be based on current integrations to be clear.

I'll remember it for next time.
