### ISSUE TITLE
feat: move "Save" button over to the left next to likes/dislikes 

### ISSUE THREAD

**Issue by King-0f-Hero** [revanced/revanced-integrations#342]
### Type

Functionality

### Issue

The standard layout of the video player has the "Save" button all the way to the right, so every time I want to add/remove a video to/from a playlist I have to scroll all the way to the right past "Share", "Remix", "Download", "Thanks" and "Clip", which are all features that get clicked on way less then Like/Dislike and "Save". I know - a seemingly small inconvenience, but for people like me who make use of playlists a lot (especially "Watch Later" so I have to remove the watched videos after) it gets very tiring and annoying after a while.

### Feature

Moving the "Save" button more to the left so you don't have to scroll to the right every time you want to add/remove a video to/from a playlist would be way more convenient - especially if you catch up on several videos in "Watch Later" and have to remove every video after watching. 

### Motivation

Having to scroll all the way to the right every time before being able to tap on "Save" gets pretty annoying after a while.
With the previously mentioned solution people could prevent this annoyance and enjoy using the playlist feature more.

**Comment by oSumAtrIX** [comment]
Disable the buttons using hide-action-buttons patch.
