### ISSUE TITLE
feat(twitch): expand block-embedded-ads with more adblocking techniques

### ISSUE THREAD

**Issue by erik9012** [ReVanced/revanced-integrations#348]
### Type

Functionality

### Issue

Right now the Twitch embedded ad patch supports proxy adblocking. But this comes with some issues such as(but not limited to)buffering, loading delay and sometimes twitch gives some purple screen and then I have to wait 30 seconds before the stream actually starts.

### Feature

What I am requesting is adding the approach of https://github.com/cleanlock/VideoAdBlockForTwitch/pull/96. It works very good for me on my desktop. It doesn't need to be the default, but a toggle for it would be nice  

### Motivation

Adding this way of adblocking of  blocking twitch ads will accomplish:
More privacy. Connecting to unknown proxies is privacy wise not a good idea
More security: Even if the owner of the proxy has no bad intentions it is still possible that senstive information gets leaked through this proxy or that scary mitm attacks appear of bad actors. Or for example the proxy owner can stop with the website and a malicious actor buys the domain which is a massive security risk
Less buffering and delays: If everything happens directly on your device(including the adblocking) then you don't need to wait for the proxy to respond
Reliability: Not dependent of the uptime of  a proxy far away, not depend of the politicial situaiton in Russia for if Twitch starts serving  ads again
 

### Additional context

All of the twitch adblocking techniques that are working right now have their pro's and cons.  This twitch adblocking technique is very effective, but will lower the twitch's stream resolution to 360p in the first 5 seconds

**Comment by oSumAtrIX** [comment]
This workaround should already have been fixed.
