### ISSUE TITLE
feat: discord integration patch

### ISSUE THREAD

**Issue by cameronmgj** [revanced/revanced-integrations#386]
### Type

Functionality

### Issue

Music status not shown in discord on mobile or desktop

### Feature

Show music currently playing in yt music, or current yt video on your discord status like Spotify does. Other YouTube music clients have this functionality but only for desktop.

### Motivation

Quality of Life, let people see what you are listening to easily, would also make revanced stand out to consumers over other yt music clients

**Comment by oSumAtrIX** [comment]
External apps should exist that can display the status.
