### ISSUE TITLE
bug: Unable to exit full screen video with back button

### ISSUE THREAD

**Issue by fraps34** [revanced/revanced-integrations#422]
### Type

Cosmetic

### Bug description

Hi, back button does not work while watching youtube full screen video on android car screen. It works in settings in other parts, I can exit the full screen video with the back button in the original youtube application. But none of the revanced versions can exit the full screen with the back button.

it was working fine on old youtube vanced and original versions.

### Steps to reproduce

yes

### Relevant log output

```shell
yes
```

### Screenshots or videos

yes

### Solution

yes

### Additional context

yes

**Comment by oSumAtrIX** [comment]
Open a proper issue in the revanced-patches repository.
