### ISSUE TITLE
feat: 2.5x speed option on Youtube

### ISSUE THREAD

**Issue by DylwinTFTW** [ReVanced/revanced-integrations#465]
### Type

Functionality

### Issue

I remember this used to be an option, and I was wondering if it could be brought back.

### Feature

Add a 2.5x speed option to the video playback patch for YouTube.

### Motivation

Sometimes I want to go faster than 2x speed, but 3x speed can be too fast.

**Comment by oSumAtrIX** [comment]
Already exists.

**Comment by DylwinTFTW** [comment]
> Already exists.

There's a playback speed patch, but it goes straight from 2.0x to 3.0x. I'm requesting that a 2.5x option be available between those.

![Screenshot_20230826-212714](https://github.com/ReVanced/revanced-integrations/assets/51421022/997663e4-9eec-4286-8ea4-20bf31563e48)

**Comment by oSumAtrIX** [comment]
You can change them in the settings.

**Comment by DylwinTFTW** [comment]
My bad, didn't know that.
