### ISSUE TITLE
Further litho blockages

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-integrations#55]
New toggles to add on litho settings:

The shelf that contains videos from other channels, when you search for a specific channel:
```
templateBlockList.add("horizontal_video_shelf")
```

The shelf that contains last posts sent by a specific channel:
```
templateBlockList.add("post_shelf")
```

**Comment by oSumAtrIX** [comment]
Can you send images to what the components match to?

**Comment by OxrxL** [comment]
> Can you send images to what the components match to?

This is post_shelf:
<img width="193" alt="Immagine 2022-07-05 115431" src="https://user-images.githubusercontent.com/108184954/177302261-cfe49bce-7c13-4498-b763-6ebb8c04dd28.png">

**Comment by OxrxL** [comment]
> Can you send images to what the components match to?

And this is horizontal_video_shelf:
<img width="188" alt="Immagine 2022-07-05 115740" src="https://user-images.githubusercontent.com/108184954/177302840-fb443d09-274e-4d17-a651-b1cb1d1a52c0.png">

**Comment by OxrxL** [comment]
Please, keep the alphabetical order LOL.

**Comment by TheJeterLP** [comment]
How do you know which component does what? Where do you get the component names?

**Comment by OxrxL** [comment]
> How do you know which component does what? Where do you get the component names?

1) There are very few components inside the list, so it's almost easy to know which is the right one.

2) Go to LithoAdRemoval.java and print the string value of method "containsAd". That's all.

**Comment by OxrxL** [comment]
You can also print the array of Bytebuffer (take UTF8 conversion already in the code, and print it).

**Comment by OxrxL** [comment]
P.S: @oSumAtrIX re-check the above posted image, I mistakenly add them in the wrong post (reversed).

**Comment by oSumAtrIX** [comment]
@TheJeterLP I recommend adding a debug log for the mentioned method

**Comment by TheJeterLP** [comment]
> @TheJeterLP I recommend adding a debug log for the mentioned method

Will do

**Comment by OxrxL** [comment]
@TheJeterLP  Ehm...suggestions? Maybe it's a good name for the videos shelf from other channels, but it's also good for channel post shelf?

**Comment by TheJeterLP** [comment]
> @TheJeterLP Ehm...suggestions? It's not too generic? Maybe it's a good name for the videos shelf from other channels, but it's also good for channel post shelf?

What do you mean?

**Comment by OxrxL** [comment]
> > @TheJeterLP Ehm...suggestions? It's not too generic? Maybe it's a good name for the videos shelf from other channels, but it's also good for channel post shelf?
> 
> What do you mean?

It'a too generic name for two blockage that have a different behaviour.

**Comment by TheJeterLP** [comment]
Okay now I see what you mean, will change that.
