### ISSUE TITLE
Finalize settings

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-integrations#56]
Well...now that the integration of the settings on the java side is completed, you need to add the missing references on the xml side (especially litho).

https://github.com/revanced/revanced-integrations/blob/main/app/src/main/res/xml/revanced_prefs.xml

**Comment by OxrxL** [comment]
This task need a translator I guess, to find the best description for new toggles.

**Comment by TheJeterLP** [comment]
> This task need a translator I guess, to find the best description for new toggles.

I speak fluent english, no translator needed :)

**Comment by OxrxL** [comment]
> > This task need a translator I guess, to find the best description for new toggles.
> 
> I speak fluent english, no translator needed :)

Well so 👍

**Comment by OxrxL** [comment]
Closed in favor of https://github.com/revanced/revanced-integrations/issues/97
