### ISSUE TITLE
Bug: Newest youtube music doesn't work correctly

### ISSUE THREAD

**Issue by Totto16** [ReVanced/revanced-integrations#634]
### Bug description

the patches for `com.google.android.apps.youtube.music` state `Any` for their version, and did work for `6.49.53` (the last of 6.x.x that I tested)

but after applying them to `7.01.52`, they fail miserably

I don't know if providing any logs might be helpful, if so I'll do that, otherwise it seems, quite a few things break (that's also not unexpected for a major version bump)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [ ] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Issue belongs in patches repo and is already reported
