### ISSUE TITLE
Another new result added

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-integrations#68]
As per established tradition, a new element (in this case shelf) has been added to the app:

"browsy_bar"

It shown in the results list, after searching for a famous actor.

<img width="186" alt="Immagine 2022-07-08 082545" src="https://user-images.githubusercontent.com/108184954/177930682-c61c4ae8-8bf8-40ab-b69b-592c9d768b5a.png">

**Comment by TheJeterLP** [comment]
Go and open a PR instead of creating issues all the time

**Comment by OxrxL** [comment]
> Go and open a PR instead of creating issues all the time

Can I put this between movie blockages or needs of another toggle?

**Comment by TheJeterLP** [comment]
Movie is fine
