### ISSUE TITLE
Show patches/integrations versions in settings

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-integrations#70]
As Vanced was showing its build number in settings, it would be useful to do so for ReVanced as well. So everyone can decide whether or not to keep a package based on the included patches/integrations.

**Comment by TheJeterLP** [comment]
This will be integrated in the manager.

**Comment by OxrxL** [comment]
> This will be integrated in the manager.

And how you know if an installed package is based on a specific mix of integrations/patches versions?

There will be a way to implement it on manager?

**Comment by TheJeterLP** [comment]
The manager builds the APK and downloads the integrations and patches. So just save that values.

**Comment by TheJeterLP** [comment]
Also we can just save a version stein from ReVanced somewhere and access that with the manager, there's plenty of possibilities.

**Comment by OxrxL** [comment]
> The manager builds the APK and downloads the integrations and patches. So just save that values.

So if I clear the manager's data, I would lose everything. 🤔

**Comment by OxrxL** [comment]
> Also we can just save a version string from ReVanced somewhere and access that with the manager, there's plenty of possibilities.

This is a better way imho.

An identifier inside the apk.
