### ISSUE TITLE
Set minimum value for ReBuffer

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-integrations#72]
ReBuffer feature need of an input value greater than 0 to work properly, otherwise it generate infinite app crashes.

This already been fixed on last Vanced 17.03.38.

**Comment by TheJeterLP** [comment]
You know how to code, create a PR instead of opening issues.

**Comment by oSumAtrIX** [comment]
Please create detailed issues, nobody will understand these

**Comment by oSumAtrIX** [comment]
> You know how to code, create a PR instead of opening issues.

Creating an issue is fine, it should be done properly or its useless.

**Comment by Sculas** [comment]
> You know how to code, create a PR instead of opening issues.

@oSumAtrIX wants issues before PRs. There's a misunderstanding here between the 2 of you.

**Comment by oSumAtrIX** [comment]
No, an issue in itself is fine as well. It is part of the workflow and also complete without a PR.

**Comment by oSumAtrIX** [comment]
A PR on the other hand is not complete without an issue in the first place (Issue -> discuss -> PR)

**Comment by Sculas** [comment]
> This already been fixed on last Vanced 17.03.38.

Has this bug been **reintroduced** or has it been **fixed** already?

**Comment by OxrxL** [comment]
> You know how to code, create a PR instead of opening issues.

Code is yours, and I don't want to place something where it's okay for me but not for you.

Anyway I edited the issue to be more clear.

**Comment by oSumAtrIX** [comment]
> > You know how to code, create a PR instead of opening issues.
> 
> Code is yours, and I don't want to place something where it's okay for me but not for you.
> 
> Anyway I edited the issue to be more clear.

Can you explain the issue, how it is related, where it originates from, and a possible solution?

**Comment by OxrxL** [comment]
> > This already been fixed on last Vanced 17.03.38.
> 
> Has this bug been **reintroduced** into the ReVanced rewrite or has it been **fixed** already?

@TheJeterLP seems to have set the minimum value to 0, and not to 1. But I'm not totally sure.

**Comment by OxrxL** [comment]
> > > You know how to code, create a PR instead of opening issues.
> > 
> > 
> > Code is yours, and I don't want to place something where it's okay for me but not for you.
> > Anyway I edited the issue to be more clear.
> 
> Can you explain the issue, how it is related, where it originates from, and a possible solution?

I already explained as well as possible.

if a value lower than 1 is set for the ReBuffer settings, this too low value always crashes the app. Because app can't buffer anything with a value lower than 1.

About solution...I don't think that I need to write it down.

**Comment by Sculas** [comment]
> Can you explain the issue,

https://github.com/revanced/revanced-integrations/blob/7de199421c37b3fd77488f60bbd5d492e3bd810e/app/src/main/java/app/revanced/integrations/patches/VideoBufferPatch.java#L15-L17
`getReBuffer` must always return 1 or higher, otherwise, the application will infinitely crash because the application can't buffer anything with a value lower than 1.

> how it is related, where it originates from

This issue used to be in Vanced. It was fixed in Vanced 17.03.38 but may have been reintroduced now with the rewrite (otherwise, why would this issue be made in the first place?).

> and a possible solution?

By coercing the value to at least 1.

**Comment by OxrxL** [comment]
To be more specific. I'm referring to these values:
![dC0cEkl9H2Pmrv4Ym14HFMtyoIuH48WqfRGwqwRButA](https://user-images.githubusercontent.com/108184954/178119093-7088ad57-e243-4650-bc1a-58750833eefa.jpg)

**Comment by OxrxL** [comment]
> but may have been reintroduced now with the rewrite (otherwise, why would this issue be made in the first place?).

Purrrfect!

P.S: Was placed there because the original modder never thought it could happen...or because he didn't care.
