### ISSUE TITLE
feat: Contributing guidelines

### ISSUE THREAD

**Issue by Aunali321** [ReVanced/revanced-integrations#78]
# 🐞 Issue

Add a contributing.md in the repo so it's easier for new developers to know contributing guidelines.

# ❗ Solution

Add a contributing.md.

# ❓ Motivation

Sets guidelines for new contributors on what to do and what not to.

**Comment by TheJeterLP** [comment]
You just did that?

**Comment by Aunali321** [comment]
I added issue templates not contributing guidelines.

**Comment by oSumAtrIX** [comment]
Both repos are seperate currently, so I'd say this one would need it's own, until we merge both repos
