### ISSUE TITLE
feat: `channel-guidelines` block

### ISSUE THREAD

**Issue by OxrxL** [revanced/revanced-integrations#84]
## 🐞 Issue

At the current state, LithoAdRemoval doesn't block channel-guidelines.
<img width="197" alt="Immagine 2022-07-17 154109" src="https://user-images.githubusercontent.com/108184954/179401274-d8e68c8e-7ecf-4389-9191-db4d09c165d7.png">

## ❗ Solution

Add tag ```channel_guidelines_entry_banner``` inside LithoAdRemoval integration.

**Comment by TheJeterLP** [comment]
Will do
